### PR TITLE
updated cadvisor version

### PR DESCRIPTION
**Pull request by cloudnautique**
Updated to latest version. Tested on centos7 and ubuntu stats are still pulled at a container and host level.

### CODE REVIEW

**Comment by cjellick** [comment]
LGTM

**Comment by alena1108** [comment]
LGTM

**Comment by ibuildthecloud** [comment]
@cloudnautique You want to update to https://github.com/rancher/cadvisor-package/releases/download/v0.19.3/cadvisor.tar.gz  That has the netgo fix.  Also I change the versioning to match cadvisor version.

**Comment by cloudnautique** [comment]
@ibuildthecloud updated.

**Comment by ibuildthecloud** [comment]
LGTM

**Pull request merged**
