### PR TITLE
Fix an issue where when auth is off if you look at projects with github/ ldap members you get a 400.

### PR DESCRIPTION
**Pull request by hibooboo2**

### CODE REVIEW

**Comment by alena1108** [comment]
LGTM

**Comment by sonchang** [comment]
Sorry James.  I'm a little too lazy to trace back the code.  Can you briefly explain the 2 use cases for the untransform() and why we ignore the transformation in one case and not the other?  Thanks!

**Comment by hibooboo2** [comment]
@sonchang the untransform method that changed really should be called transform as it calls transform which ultimately validates that the identity is valid. 
But in one case we want to throw an error another we do not.

**Comment by hibooboo2** [comment]
The case where we do is if it is listing. don't is when they are creating members

**Comment by sonchang** [comment]
Yeah.  I was able to gather that much from the code changes.  But why check for the listing but not when creating members?

**Comment by hibooboo2** [comment]
i do check when listing but if it fails it isnt an error that should return 400 it should change the displayed result. But on creation it should 400

**Comment by sonchang** [comment]
Got it.  Thanks!  LGTM

**Pull request merged**
