### PR TITLE
Adding CATTLE_IPTABLES_INTERMEDIARY_CHAIN support if the variable is …

### PR DESCRIPTION
**Pull request by stresler**
…defined.

PR so we can discuss Issue #1150

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@stresler I wonder if we could make this simpler in that we just always have a special chain that call first.  So if the chain doesn't exist we create it (same as you do here), but otherwise we don't alter the chain.  Then there is no real configuration the user has to do of the agent, they would just have to know to put rules in that special chain if they want prefiltering.

**Comment by stresler** [comment]
That would totally suffice. I could modify this patch if you want. I expect that special chain would just have a similar catchall at the bottom of it to get everything to CATTLE_PREROUTING next?

**Comment by ibuildthecloud** [comment]
@stresler If you could modify this PR that would be great.  It's basically the same approach and structure that you specified, but just assume there is no configuration an CATTLE_IPTABLES_INTERMEDIARY_CHAIN is always set to something fixed.

**Comment by stresler** [comment]
If this suits I'll squash it. Do you guys have a commit message methodology you prefer?

**Comment by ibuildthecloud** [comment]
@stresler We prefer PRs to be squashed.

**Comment by ibuildthecloud** [comment]
@stresler And not picky about messages.

**Comment by stresler** [comment]
Well, I did something wrong here.  I'll need to figure out how I mangled this PR first thing tomorrow though. Need to head out for the day.

**Comment by stresler** [comment]
I'm not sure that this PR is causing a 'No Route To Host' in Drone.  Is there a way to trigger a re-run of that test?

**Comment by stresler** [comment]
Hold off on this. Experimenting some more.

**Comment by stresler** [comment]
This is not going to be the right way to deal with this issue. I'll update #1150

**Comment by vincent99** [comment]
FYI the "no route to host" thing is just our drone being broken today.

**Pull request closed without merging**
