### PR TITLE
add engineOpts and dockerVersion fields in machine

### PR DESCRIPTION
**Pull request by wlan0**
@cjellick @alena1108 

These fields are required for allowing a user to specify a docker version, and other docker engine options when performing the 'Add host' action for a cloud provider.

### CODE REVIEW

**Comment by alena1108** [comment]
@wlan0 do we ever expect those fields to be set by the user? If so, we should add the permissions to user-auth.

**Comment by wlan0** [comment]
These fields are required for allowing a user to specify a docker version, and other docker engine options when performing the 'Add host' action for a cloud provider.

**Comment by wlan0** [comment]
@alena1108 Set 'create' permissions for "project" user on these fields. The "project" user will create these fields.

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
