### PR TITLE
Metadata support

### PR DESCRIPTION
**Pull request by alena1108**
This PR also requires metadata service packaging

### CODE REVIEW

**Comment by alena1108** [comment]
@ibuildthecloud @vincent99 could you please validate answers.json content. I've implemented it based on the screenshot shared by Darren from the meeting two of you had. Could of extra fields that I've added:

* "state" for the container. As we are going to push all the containers data (except for removed ones). it might be important to display the state 
* "vip" for the service
* "kind" for the service
* "ports" field to the services (publicPort:privatePort format). We also have it per container (host:publicPort:privatePort format)
* use map instead of array for storing the "links". As link can have an alias

```
{
    "default": {
        "stacks": [
            {
                "environmentName": "Default",
                "name": "Default",
                "services": [
                    "regular",
                    "lb",
                    "external",
                    "externalwhost",
                    "alias"
                ]
            }
        ],
        "services": [
            {
                "name": "regular",
                "stackName": "Default",
                "kind": "service",
                "hostName": null,
                "vip": null,
                "ipAddresses": [],
                "sidekicks": [],
                "containers": [
                    "Default_regular_1"
                ],
                "links": {
                    "alias": "alias"
                },
                "ports": []
            },
            {
                "name": "lb",
                "stackName": "Default",
                "kind": "loadBalancerService",
                "hostName": null,
                "vip": null,
                "ipAddresses": [],
                "sidekicks": [],
                "containers": [
                    "Lb Agent"
                ],
                "links": {
                    "lb": "regular"
                },
                "ports": [
                    "100"
                ]
            },
            {
                "name": "external",
                "stackName": "Default",
                "kind": "externalService",
                "hostName": null,
                "vip": null,
                "ipAddresses": [
                    "172.18.0.1"
                ],
                "sidekicks": [],
                "containers": [],
                "links": {},
                "ports": []
            },
            {
                "name": "externalwhost",
                "stackName": "Default",
                "kind": "externalService",
                "hostName": "google.com",
                "vip": null,
                "ipAddresses": [],
                "sidekicks": [],
                "containers": [],
                "links": {},
                "ports": []
            },
            {
                "name": "alias",
                "stackName": "Default",
                "kind": "dnsService",
                "hostName": null,
                "vip": null,
                "ipAddresses": [],
                "sidekicks": [],
                "containers": [],
                "links": {
                    "alias": "lb"
                },
                "ports": []
            }
        ],
        "containers": [
            {
                "name": "Default_regular_1",
                "primaryIp": "10.42.65.14",
                "ips": [
                    "10.42.65.14"
                ],
                "ports": [],
                "serviceName": "regular",
                "state": "running"
            },
            {
                "name": "Lb Agent",
                "primaryIp": "10.42.217.3",
                "ips": [
                    "10.42.217.3"
                ],
                "ports": [
                    "127.0.0.1:100:100"
                ],
                "serviceName": "lb",
                "state": "running"
            }
        ]
    },
    "10.42.217.3": {
        "container": {
            "name": "Lb Agent",
            "primaryIp": "10.42.217.3",
            "ips": [
                "10.42.217.3"
            ],
            "ports": [
                "127.0.0.1:100:100"
            ],
            "serviceName": "lb",
            "state": "running"
        },
        "service": {
            "name": "lb",
            "stackName": "Default",
            "kind": "loadBalancerService",
            "hostName": null,
            "vip": null,
            "ipAddresses": [],
            "sidekicks": [],
            "containers": [
                "Lb Agent"
            ],
            "links": {
                "lb": "regular"
            },
            "ports": [
                "100"
            ]
        },
        "stack": {
            "environmentName": "Default",
            "name": "Default",
            "services": [
                "regular",
                "lb",
                "external",
                "externalwhost",
                "alias"
            ]
        }
    },
    "10.42.65.14": {
        "container": {
            "name": "Default_regular_1",
            "primaryIp": "10.42.65.14",
            "ips": [
                "10.42.65.14"
            ],
            "ports": [],
            "serviceName": "regular",
            "state": "running"
        },
        "service": {
            "name": "regular",
            "stackName": "Default",
            "kind": "service",
            "hostName": null,
            "vip": null,
            "ipAddresses": [],
            "sidekicks": [],
            "containers": [
                "Default_regular_1"
            ],
            "links": {
                "alias": "alias"
            },
            "ports": []
        },
        "stack": {
            "environmentName": "Default",
            "name": "Default",
            "services": [
                "regular",
                "lb",
                "external",
                "externalwhost",
                "alias"
            ]
        }
    }
}
```

**Comment by vincent99** [comment]
- `state` means you're going to have to push down a new answers.json every time a container's state changes... Seems like potentially not a good idea for performance.
- We usually do `hostname` as one word, not inter-caps two.  Even though it's next to `ipAddresses` and `stackName` :smile:
- Should all the keys be snake_case?  They all turn into URLs (e.g. `/services/0/stack_name/`) so case-sensitivity is not very desirable.

**Comment by sonchang** [comment]
If the containers have the stackName in addition to the serviceName, then I should be able to still get all the info I need by just querying all the containers.  Rather than query both "services" and "containers" and combine the resulting data.

**Comment by alena1108** [comment]
@vincent99 

>> state means you're going to have to push down a new answers.json every time a container's state changes... Seems like potentially not a good idea for performance.

Not exactly. Config update is triggered by the list of predefined processes, not on every state change. I still think displaying the state might be a good idea as there might be cases when we want to return Stopped instances in metadata response, but we want to signal the client that the instance is actually stopped

>>We usually do hostname as one word, not inter-caps two. Even though it's next to ipAddresses and stackName :smile:

One liner change, np :) 

>> Should all the keys be snake_case? They all turn into URLs (e.g. /services/0/stack_name/) so case-sensitivity is not very desirable.

will fix

**Comment by alena1108** [comment]
@sonchang 

will fix

**Comment by sonchang** [comment]
quick question.  If I query for 'container', will this just bring up the containers running on this host?  Since I'll need container information for all containers within a service.  @vincent99 @ibuildthecloud

**Comment by alena1108** [comment]
@sonchang it will bring up the containers for the service. But I also see that having host_id field on container would be a good idea.

**Comment by vincent99** [comment]
> Not exactly. Config update is triggered by the list of predefined processes, not on every state change.

Ok, but if you provide it users will expect it to be accurate, and updated in a timely manner.  You could imagine someone using that to do autoscaling or monitoring. 

> it will bring up the containers for the service.

Am I missing something?  `/{version}/container` is the information about the (singular) container that is making the request.  It doesn't tell you about the other containers that make up the service.

There doesn't seem to be any simple way to get "all the containers for the current service", you'd want to use JSON or it will be many requests.. `/{version}/containers/`.filter((container) => { return container.serviceName == `/{version}/service/name`; })

Seems like there an issue here with service names not being unique across stacks...  We used `stackName/serviceName` as the primary identifier for labels because of that.

**Comment by ibuildthecloud** [comment]
@alena1108 Let's drop state.  One thing that has come up in discussion w/ users is being about to get the host labels is useful.  I don't know where we should put that.  @vincent99 ideas?

**Comment by vincent99** [comment]
`/{version}/host` with info about the current host?  Any reason why not show labels for containers & services too?

**Comment by alena1108** [comment]
@vincent99 no reason, just missed it - labels. I'll add the host info as well.

@ibuildthecloud I'll drop the state

**Comment by ibuildthecloud** [comment]
Labels for services and containers would be good.  Why do we have network/volumes from and sidekick.  I'd like to start with a minimum amount and then add things.  I can't really think why is need this metadata

**Comment by alena1108** [comment]
@vincent99 @sonchang sorry, overlooked "container" as "service".  So under container you will see the information about only this container + its service.

Its when you query service, you get the info about all the containers of this service, not only containers running on this host.

**Comment by alena1108** [comment]
@ibuildthecloud I can remove sidekicks for now, and leave volumes_from, network_from

**Comment by ibuildthecloud** [comment]
Id like to drop networks/container from.  We can always easily add more fields.  But removing is hard

**Comment by alena1108** [comment]
@ibuildthecloud ok, will leave sidekicks and remove the other two

**Comment by ibuildthecloud** [comment]
Wait @alena1108 do we need sidekick?  I'd still want to remove that too

**Comment by alena1108** [comment]
@ibuildthecloud it was on the whiteboard drawing from your meeting with @vincent99 ...but sure, can remove that one

**Comment by ibuildthecloud** [comment]
@alena1108 Oh, maybe there was a reason.  Let's keep it

**Comment by alena1108** [comment]
@ibuildthecloud if there is a use case requiring displaying sidekicks, do you think volumesFrom/networksFrom can be relevant too? As people often use sidekicks in volumesFrom/networkFrom context

**Comment by ibuildthecloud** [comment]
I think the reason we put sidekick is because a sidekick service is not a real service, so we wanted to know what the real service was.  I'd still avoid network/volumes.

**Comment by alena1108** [comment]
@ibuildthecloud ok

**Comment by ibuildthecloud** [comment]
@vincent99 @alena1108 seems like we should add a DNS name for 169.254.169.250.  Ideas?? We could just use `rancher-metadata`.  I thought maybe `metadata` but that might be too generic.

**Comment by alena1108** [comment]
@ibuildthecloud @vincent99 I like rancher-metadata better as a) it implies its our internal server b) it would never conflict with anything else

**Comment by vincent99** [comment]
`rancher-metadata` sounds good, if you're willing to call it metadata and not carefully-worded-introspection-API.

**Comment by ibuildthecloud** [comment]
Metadata is fine.  Introspection api backfired.  People thought it sounded too complicated.

**Comment by alena1108** [comment]
Added "version" field to "default" section:

```
{"default": {
 	"version": "2-aae727c7fbc55f447f3e8c49cc4e50dd806913bc2cbd72e34e64649f294ca977",
...........
```

@sonchang

**Comment by alena1108** [comment]
Dont merge yet, going to address some performance issues during the weekend

**Comment by alena1108** [comment]
Performance issue is addressed, ready to be merged.

**Pull request merged**
