### PR TITLE
Rancher private registry support in k8s

### PR DESCRIPTION
**Pull request by alena1108**
https://github.com/rancher/kubernetes/pull/8

### CODE REVIEW

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/4529

**Comment by ibuildthecloud** [comment]
Hmmmmm.  Definitely don't like the idea of yet another role.  Thinking....

**Comment by alena1108** [comment]
@ibuildthecloud reworked the approach based on the discussion we've had.

**Comment by alena1108** [comment]
@ibuildthecloud introduced "environmentAdmin" agent role

**Comment by alena1108** [comment]
Drone error is resolved by this PR: https://github.com/rancher/cattle/pull/1688

**Pull request merged**
