### PR TITLE
do not translate bind mounts to v2 volumes

### PR DESCRIPTION
**Pull request by alena1108**
https://github.com/rancher/rancher/issues/7070

@deniseschannon @joshwget

### CODE REVIEW

**Comment by joshwget** [comment]
It looks like we actually do this in libcompose by checking if the left string is an absolute path (https://github.com/docker/libcompose/blob/master/lookup/file.go#L61). Can we do something like that for consistency? There seems to be a similar function in Java http://stackoverflow.com/a/28526097.

**Comment by alena1108** [comment]
@joshwget sure, let me test it

**Comment by alena1108** [comment]
@joshwget updated the PR + added extra verification to the test

**Comment by joshwget** [comment]
LGTM!

**Pull request merged**
