### PR TITLE
fix the issue that agent stuck in upgrade loop

### PR DESCRIPTION
**Pull request by loganhz**
[rancher/rancher#9164](https://github.com/rancher/rancher/issues/9164)

### CODE REVIEW

**Comment by yasker** [comment]
Commit message:
1. Describe what's the issue and how you fixed it.
2. Add a reference to the bug.

**Comment by yasker** [comment]
@loganhz Why this container was running as a daemon at first place?

**Comment by loganhz** [comment]
@yasker I don't know the reason.  I think it shouldn't be a daemon.  This issue only happens when the host load is very high or docker responses very slow.

**Comment by yasker** [comment]
@loganhz https://github.com/rancher/cattle/commit/caa4828c101a0fb2dc66f4aa63040923abb316e2

**Comment by loganhz** [comment]
hi @ibuildthecloud, I saw you have added `-d` in [`caa4828`](https://github.com/rancher/cattle/commit/caa4828c101a0fb2dc66f4aa63040923abb316e2) two years ago. May I know the reason for it? 

@cjellick found that `Investigation revealed that there appears to be a race condition in our upgrade logic wherein if the rancher-agent-upgarde container takes about five seconds or longer to complete, rancher-agent removes and re-adds it.`

**Comment by cjellick** [comment]
Change scares me. I don't have context on why it was changed. @ibuildthecloud explicitly made this change, so I bet there's a reason. I'd prefer he gave input

**Comment by yasker** [comment]
I think @ibuildthecloud made that change so we can kill stuck container, which is probably more important than the race condition happens occasionally.

Still, need @ibuildthecloud 's input.

But the only other fix I can think of is increasing the timeout, which not I preferred usually.

**Comment by yasker** [comment]
@loganhz Can you come up with another approach to fix the issue? Except increasing the timeout.

**Comment by loganhz** [comment]
Changed to `timeout 60 docker run --privileged --name rancher-agent-upgrade -v /var/run/docker.sock:/var/run/docker.sock ${REQUIRED_IMAGE} upgrade`

**Comment by deniseschannon** [comment]
Closing as both @cjellick and @ibuildthecloud were uncomfortable with this change. Attempting a different method.

**Pull request closed without merging**
