### PR TITLE
Tests for password validation

### PR DESCRIPTION
**Pull request by mrajashree**
Adds tests for `api.auth.local.validate.url` setting on top of @cjellick  v1 schemas PR: https://github.com/rancher/cattle/pull/2130

### CODE REVIEW

**Comment by mrajashree** [comment]
The TF `test_link_remove_restore` seems unrelated
@cjellick @ibuildthecloud

**Comment by cjellick** [comment]
addresses https://github.com/rancher/rancher/issues/6358

**Comment by cjellick** [comment]
LGTM

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues?q=is%3Aopen+is%3Aissue+assignee%3Amrajashree+milestone%3A%22Release+1.2.0%22

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues/5973

**Pull request merged**
