### PR TITLE
Container name unique per environment

### PR DESCRIPTION
**Pull request by alena1108**
https://github.com/rancher/rancher/issues/7384

@ibuildthecloud @vincent99 still uncertain whether putting this restriction on API side is correct, given that internally we do allow duplicated names (during in service upgrade use case, failed health check instance recreate, etc)

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
I think it's fine to attempt to prevent this knowing that we really can't stop it fully.

**Comment by cjellick** [comment]
What's the point of disallowing it? Are we still going to allow null names?

**Comment by vincent99** [comment]
Containers can go on stacks which now have to have unique (and not null) names for DNS

**Comment by cjellick** [comment]
What do you mean "can go on stacks" @vincent99?

**Comment by alena1108** [comment]
@vincent99 I didn't put not null restriction on the container name yet, should I do it?

**Pull request merged**
