### PR TITLE
WIP - DNM Fix ipsec config race

### PR DESCRIPTION
**Pull request by dx9**
@ibuildthecloud 

This doesn't seem to cause direct test failures but shows up in the logs.

SimulatorConfigUpdateProcessor tries to download the ipsec config before AgentInstanceIpsecNetworkServiceCreate has defined the key. This causes the template to fail because ipsecKey is undefined.

Unsure if this is expected behaviour. If so can we change the key in the template to be optional to avoid the log error?

If it's a real issue, another idea would be to try multiple times to read the key in IpsecInfoFactory (seems lame).

Thoughts?

racy logs: https://gist.github.com/dx9/fd4c91b112919be7131751bade55ddd8

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@dx9 out of curiosity.  Are you running on a really fast machine?

**Comment by ibuildthecloud** [comment]
Generally we just make things optional (check for null).  Being that most everything is eventually consistent it is possible we download config before something has been defined.  The issue occurs is if we don't end up triggering a config update after the previously set value becomes set.

So in sort, the first option seems good.

**Comment by dx9** [comment]
yeppers, R710

Sounds good. Thanks for taking a look.

**Comment by ibuildthecloud** [comment]
Sounds like we need to run our CI on faster machines 🙂

**Comment by alena1108** [comment]
@ibuildthecloud @leodotcloud is this still relevant given that psk.txt.ftl file is gone from cattle code base?

**Pull request closed without merging**
