### PR TITLE
add resource requests to allocation error message

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
for https://github.com/rancher/rancher/issues/8636

**Comment by cjellick** [comment]
@StrongMonkey what does the message look like when it fails for a combination of reasons. Specifically, what is the error message in this scenario?
1. have two hosts, one with label foo=bar
2. deploy a container that uses port 80 on that host
3. create a service of scale=1 that needs port 80 and has a label constraint that it must land on a host with a foo=bar label?

**Comment by StrongMonkey** [comment]
The msg is described in the issue linked. @cjellick

**Comment by cjellick** [comment]
Let's make it more user friendly:
Change:
```
Allocation failed: needs host with label foo: bar, ResourceRequests: [ports: [8080:8080/tcp], ResourceType: instanceReservation, Amount: 1]
```
to:
```
Allocation failed: needs host with label foo: bar and resources constraints: [ports: 8080:8080/tcp, 1 instanceReservation]
```

**Comment by cjellick** [comment]
Changed it again, want `and resource constraints[ 80/tcp, 90/tcp ports, 1 instanceReservation]`

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
