### PR TITLE
add rancherCompose and dockerCompose fields to environment resource

### PR DESCRIPTION
**Pull request by wlan0**
@cjellick, @ibuildthecloud  - This adds the `import` field to service. This field will hold the bytes of rancher-compose.yml file.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
I don't think this needs to be a db column.  Also don't we need two fields?  One for docker-compose and another for rancher-compose

**Comment by wlan0** [comment]
@ibuildthecloud Are you suggesting that this field be in the `data` column?  

 I originally intended to encode both files into a single archive and base64 encode the bytes and set it to this field. I apologize for not mentioning that accurately in my previous description.

**Comment by ibuildthecloud** [comment]
I don't think I'd want them archived.  It just makes it harder to interact with the API of they need to be archived.

**Comment by wlan0** [comment]
@ibuildthecloud I've changed this commit entirely from its initial form.

There are two new fields - `rancherCompose` and `dockerCompose` in the `env` resource

**Comment by ibuildthecloud** [comment]
These don't need to be DB fields.

**Comment by wlan0** [comment]
test_container_port_start failed. It is not related to this PR.

**Pull request merged**
