### PR TITLE
Default batch size to 1 for system services

### PR DESCRIPTION
**Pull request by alena1108**

### CODE REVIEW

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/10103

**Comment by ibuildthecloud** [comment]
Does this set to always 1 or default to 1?

**Comment by alena1108** [comment]
@ibuildthecloud "set to always 1" when system. It is already defaulted to 1 in the API, therefor was my question whether we should default it to 1 instead of 2 for system services on rancher-compose side.

**Comment by alena1108** [comment]
Closing as the fix will be done on the rancher-compose side https://github.com/rancher/rancher-compose-executor/pull/135

**Pull request closed without merging**
