### PR TITLE
Reverting the changes for service linkName validation

### PR DESCRIPTION
**Pull request by prachidamle**
Now the linkName allows any characters, no length limits, does not follow the DNS label RFC standard

### CODE REVIEW

**Comment by prachidamle** [comment]
@ibuildthecloud please review the reverted code

**Comment by vincent99** [comment]
Okay we can argue about allowing dots but it *definitely* shouldn't just allow arbitrary garbage.

**Comment by ibuildthecloud** [comment]
@vincent99 I think _ and . should be allowed.  That's it

**Comment by prachidamle** [comment]
@vincent99 @ibuildthecloud opening another PR to allow _ and .  , closing this one

**Comment by vincent99** [comment]
And 1-253 characters, not consecutive dots, not starting with a dot...

**Comment by ibuildthecloud** [comment]
@vincent99 Yeah, sorry, I mean the only thing we should relax is _ and . but otherwise validate everything else.

**Pull request closed without merging**
