### PR TITLE
fix id obfuscator 1.6

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by cjellick** [comment]
Generally, I don't like the approach passing the formatted id into the constraints as a string. You should pass the formatter into the constraints and only use the formatter in the toString() method

**Comment by StrongMonkey** [comment]
not sure if tests seem unrelated

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/8653

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
