### PR TITLE
container, stack, service name lowercased in metadata

### PR DESCRIPTION
**Pull request by alena1108**
@vincent99

### CODE REVIEW

**Comment by vincent99** [comment]
LGTM, see also https://github.com/rancher/rancher-metadata/pull/22

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/1908

**Comment by ibuildthecloud** [comment]
@alena1108 I'm afraid of NPE's, are they definitely not possible?

**Comment by alena1108** [comment]
@ibuildthecloud min length for service/stack name is 1; no such check for container. I'll add not null check just to be safe

**Pull request merged**
