### PR TITLE
some validations on names

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/10173

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/10177

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/10186

**Comment by alena1108** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches

**Pull request closed without merging**
