### PR TITLE
Postgres Support

### PR DESCRIPTION
**Pull request by dx9**
Initially started over in #677. Creating a new PR because I started using branches.

It passes the 'lite' test plan. 

The 'full' plan starts to fail when it gets to core/test_svc_discovery.py with duplicate key database errors. 

Still needs some looking into.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Wow, this is great progress.

**Comment by dx9** [comment]
@ibuildthecloud tks, it's coming along

I've been testing it... It can appear to run clean if test_svc_discovery.py::test_service_add_remove_link and test_svc_discovery.py::test_destroy_service_instance are disabled. Only tests I've found that fail consistently.

Tried to get a data inconsistency situation to show up on Drone but got tired of kicking it. 

Found this by stress testing a duplicate key error during test_allocation.py::test_host_vnet_association. Here are some table dumps of resource_pool from mysql and pgsql after running.

MYSQL STATE
+----+------+------------+--------------+--------------------------------------+-------------+-----------+---------------------+---------+-------------+------+-----------+---------+-------------------+------------+----------+-----------+
| id | name | account_id | kind         | uuid                                 | description | state     | created             | removed | remove_time | data | pool_type | pool_id | item              | owner_type | owner_id | qualifier |
+----+------+------------+--------------+--------------------------------------+-------------+-----------+---------------------+---------+-------------+------+-----------+---------+-------------------+------------+----------+-----------+
|  1 | NULL |       NULL | resourcePool | a50c2beb-4695-4dba-b442-a7dd1e68fd05 | NULL        | requested | 2015-08-14 19:05:08 | NULL    | NULL        | {}   | global    |       1 | 02:ed:b8          | network    |        1 | macPrefix |
|  2 | NULL |       NULL | resourcePool | 32aa309e-c926-42f0-8abe-603c078519cc | NULL        | requested | 2015-08-14 19:05:08 | NULL    | NULL        | {}   | global    |       1 | 02:9e:69          | network    |        4 | macPrefix |
|  3 | NULL |       NULL | resourcePool | f3184c38-8c06-4bfc-9bbc-6d570f077456 | NULL        | requested | 2015-08-14 19:05:08 | NULL    | NULL        | {}   | global    |       1 | 02:24:0b          | network    |        5 | macPrefix |
|  4 | NULL |       NULL | resourcePool | 67d20b90-f605-4674-9b4b-2a55e830dbf9 | NULL        | requested | 2015-08-14 19:05:08 | NULL    | NULL        | {}   | global    |       1 | 02:5d:0b          | network    |        3 | macPrefix |
|  5 | NULL |       NULL | resourcePool | ae09a545-73bf-41cd-9fd2-a7bca4776a94 | NULL        | requested | 2015-08-14 19:05:08 | NULL    | NULL        | {}   | global    |       1 | 02:88:ea          | network    |        2 | macPrefix |
|  6 | NULL |       NULL | resourcePool | bc514b59-33fc-4aa6-9e44-8afd7e36f21a | NULL        | requested | 2015-08-14 19:05:34 | NULL    | NULL        | {}   | network   |       4 | 02:9e:69:bd:76:ea | nic        |        1 | mac       |
|  7 | NULL |       NULL | resourcePool | 53ca8d23-f83d-4b58-8144-430533017867 | NULL        | requested | 2015-08-14 19:05:34 | NULL    | NULL        | {}   | network   |       4 | 02:9e:69:75:11:02 | nic        |        3 | mac       |
|  8 | NULL |       NULL | resourcePool | 555df018-880f-4197-a978-bc8b2570a7a9 | NULL        | requested | 2015-08-14 19:05:34 | NULL    | NULL        | {}   | network   |       4 | 02:9e:69:ed:b9:d2 | nic        |        2 | mac       |
|  9 | NULL |       NULL | resourcePool | ded42f1b-34be-4e84-997f-8abb439e9a90 | NULL        | requested | 2015-08-14 19:06:01 | NULL    | NULL        | {}   | global    |       1 | 02:ae:25          | network    |        6 | macPrefix |
| 10 | NULL |       NULL | resourcePool | 73c1ce56-20a6-48a0-a1a3-855a80af1b8f | NULL        | requested | 2015-08-14 19:06:01 | NULL    | NULL        | {}   | global    |       1 | 02:ee:9c          | network    |        9 | macPrefix |
| 11 | NULL |       NULL | resourcePool | ce8a6db9-c0bd-4bb6-a6c3-1e3eec1074ad | NULL        | requested | 2015-08-14 19:06:01 | NULL    | NULL        | {}   | global    |       1 | 02:9a:dd          | network    |        8 | macPrefix |
| 12 | NULL |       NULL | resourcePool | 1d46a843-d94c-4a79-960c-fc76110cf1ff | NULL        | requested | 2015-08-14 19:06:01 | NULL    | NULL        | {}   | global    |       1 | 02:31:8e          | network    |       10 | macPrefix |
| 13 | NULL |       NULL | resourcePool | 546c445c-a034-4c4a-bac0-06568021c9e3 | NULL        | requested | 2015-08-14 19:06:01 | NULL    | NULL        | {}   | global    |       1 | 02:65:da          | network    |        7 | macPrefix |
| 14 | NULL |       NULL | resourcePool | 0c4fe5ad-49df-44ae-8cd9-867a248b0697 | NULL        | requested | 2015-08-14 19:06:08 | NULL    | NULL        | {}   | global    |       1 | 02:23:f0          | network    |       11 | macPrefix |
| 15 | NULL |       NULL | resourcePool | 82bac5d4-5080-4097-8168-efacd8b85e22 | NULL        | requested | 2015-08-14 19:06:08 | NULL    | NULL        | {}   | subnet    |       3 | 192.168.0.5       | ipAddress  |        8 | default   |
| 16 | NULL |       NULL | resourcePool | 40b8a29c-6e70-4164-907d-946b231f1ab2 | NULL        | requested | 2015-08-14 19:06:08 | NULL    | NULL        | {}   | network   |      11 | 02:23:f0:6a:64:24 | nic        |        4 | mac       |
| 18 | NULL |       NULL | resourcePool | f2429a2b-4e81-403a-ba75-d9e49b2f9089 | NULL        | requested | 2015-08-14 19:06:09 | NULL    | NULL        | {}   | subnet    |       3 | 192.168.0.3       | ipAddress  |        9 | default   |
| 19 | NULL |       NULL | resourcePool | 60e7ffc5-2224-43b1-8452-d490b2f314f5 | NULL        | requested | 2015-08-14 19:06:09 | NULL    | NULL        | {}   | network   |      11 | 02:23:f0:a8:55:8d | nic        |        5 | mac       |
| 21 | NULL |       NULL | resourcePool | 71c17795-9750-423e-9994-cc455f965c9a | NULL        | requested | 2015-08-14 19:06:09 | NULL    | NULL        | {}   | subnet    |       3 | 192.168.0.4       | ipAddress  |       10 | default   |
| 22 | NULL |       NULL | resourcePool | 2606d80c-050a-43f5-9deb-95909fbc766b | NULL        | requested | 2015-08-14 19:06:09 | NULL    | NULL        | {}   | network   |      11 | 02:23:f0:ab:8c:f6 | nic        |        6 | mac       |
| 23 | NULL |       NULL | resourcePool | e0101c07-511f-48f1-b45d-cdbbf6030ad6 | NULL        | requested | 2015-08-14 19:06:10 | NULL    | NULL        | {}   | subnet    |       4 | 192.168.2.163     | ipAddress  |       11 | default   |
| 24 | NULL |       NULL | resourcePool | 8b0ccd6e-635e-4172-a8dd-d54c6674e9f2 | NULL        | requested | 2015-08-14 19:06:10 | NULL    | NULL        | {}   | network   |      11 | 02:23:f0:4b:5c:9f | nic        |        7 | mac       |
| 25 | NULL |       NULL | resourcePool | 01394cb2-128d-46af-a32b-977def917986 | NULL        | requested | 2015-08-14 19:06:10 | NULL    | NULL        | {}   | subnet    |       4 | 192.168.2.220     | ipAddress  |       12 | default   |
| 26 | NULL |       NULL | resourcePool | 9ae5bdab-9248-41f0-aa37-1fe9000b668c | NULL        | requested | 2015-08-14 19:06:10 | NULL    | NULL        | {}   | network   |      11 | 02:23:f0:57:91:3e | nic        |        8 | mac       |
| 27 | NULL |       NULL | resourcePool | d6d3d4bb-429f-4cfa-abb9-30cb0af789e5 | NULL        | requested | 2015-08-14 19:06:11 | NULL    | NULL        | {}   | subnet    |       4 | 192.168.2.149     | ipAddress  |       13 | default   |
| 28 | NULL |       NULL | resourcePool | 54b8f74c-5f6b-44da-8a07-9a3df3f97aab | NULL        | requested | 2015-08-14 19:06:11 | NULL    | NULL        | {}   | network   |      11 | 02:23:f0:fe:aa:44 | nic        |        9 | mac       |
+----+------+------------+--------------+--------------------------------------+-------------+-----------+---------------------+---------+-------------+------+-----------+---------+-------------------+------------+----------+-----------+
+----------+
| count(*) |
+----------+
|       26 |
+----------+
PGSQL STATE
 id | name | account_id |     kind     |                 uuid                 | description |   state   |          created           | removed | remove_time | data | pool_type | pool_id |       item        | owner_type | owner_id | qualifier 
----+------+------------+--------------+--------------------------------------+-------------+-----------+----------------------------+---------+-------------+------+-----------+---------+-------------------+------------+----------+-----------
  1 |      |            | resourcePool | 8a3ccdeb-ae5d-4eb7-99e6-789085228364 |             | requested | 2015-08-14 19:08:19.71+00  |         |             | {}   | global    |       1 | 02:0d:fe          | network    |        3 | macPrefix
  2 |      |            | resourcePool | f93a8e20-86e5-4930-a95d-7bb50421d7b9 |             | requested | 2015-08-14 19:08:19.769+00 |         |             | {}   | global    |       1 | 02:fa:ad          | network    |        2 | macPrefix
  3 |      |            | resourcePool | ee7e0643-1a15-4289-92d3-f9ae05e39d60 |             | requested | 2015-08-14 19:08:19.879+00 |         |             | {}   | global    |       1 | 02:f3:5a          | network    |        1 | macPrefix
  4 |      |            | resourcePool | d0b1f854-895b-47b1-9fee-c43040e7aa9b |             | requested | 2015-08-14 19:08:19.966+00 |         |             | {}   | global    |       1 | 02:99:11          | network    |        5 | macPrefix
  5 |      |            | resourcePool | c2ad2c3c-a4ca-46b7-9d15-2fbf04dd8256 |             | requested | 2015-08-14 19:08:19.972+00 |         |             | {}   | global    |       1 | 02:a2:33          | network    |        4 | macPrefix
  6 |      |            | resourcePool | 773a4911-42e8-488e-b2f6-9e9cd91b68b8 |             | requested | 2015-08-14 19:09:10.307+00 |         |             | {}   | global    |       1 | 02:e2:fb          | network    |       10 | macPrefix
  7 |      |            | resourcePool | 4c665ce0-ae17-41cd-a0d8-690bdaf80177 |             | requested | 2015-08-14 19:09:10.284+00 |         |             | {}   | global    |       1 | 02:05:25          | network    |        8 | macPrefix
  8 |      |            | resourcePool | 7b68c908-d5aa-4a19-aeca-6933f80bf3ff |             | requested | 2015-08-14 19:09:10.299+00 |         |             | {}   | global    |       1 | 02:24:99          | network    |        9 | macPrefix
  9 |      |            | resourcePool | 787435aa-8974-40b6-a32a-afd6dd6c373a |             | requested | 2015-08-14 19:09:10.318+00 |         |             | {}   | global    |       1 | 02:2d:8d          | network    |        6 | macPrefix
 10 |      |            | resourcePool | 811fe60f-7cf2-4e56-b5f7-bf614204d912 |             | requested | 2015-08-14 19:09:10.434+00 |         |             | {}   | global    |       1 | 02:0c:76          | network    |        7 | macPrefix
 11 |      |            | resourcePool | c375a970-a721-4891-9bee-cdda9b9e38de |             | requested | 2015-08-14 19:09:14.185+00 |         |             | {}   | global    |       1 | 02:a3:57          | network    |       11 | macPrefix
 12 |      |            | resourcePool | a7cb845d-e1ff-410a-884f-ae233b2c778a |             | requested | 2015-08-14 19:09:15.384+00 |         |             | {}   | subnet    |       3 | 192.168.0.5       | ipAddress  |        5 | default
 13 |      |            | resourcePool | de25882a-4b6a-4b77-b9e5-6663d41f44fc |             | requested | 2015-08-14 19:09:15.414+00 |         |             | {}   | network   |      11 | 02:a3:57:9e:97:bd | nic        |        1 | mac
 15 |      |            | resourcePool | 0fcf5b24-7b9d-42a6-b3db-658a83b8f0bf |             | requested | 2015-08-14 19:09:16.071+00 |         |             | {}   | subnet    |       3 | 192.168.0.3       | ipAddress  |        6 | default
 16 |      |            | resourcePool | 482c5a0d-2ff7-49fe-8149-63f029abcad0 |             | requested | 2015-08-14 19:09:16.084+00 |         |             | {}   | network   |      11 | 02:a3:57:a4:f9:a0 | nic        |        2 | mac
 17 |      |            | resourcePool | 24109581-8b2d-4b56-ae8d-242c9cb7b400 |             | requested | 2015-08-14 19:09:16.55+00  |         |             | {}   | subnet    |       3 | 192.168.0.4       | ipAddress  |        7 | default
 18 |      |            | resourcePool | 4e534974-55f3-41b5-8f1a-a6bc095b8737 |             | requested | 2015-08-14 19:09:16.561+00 |         |             | {}   | network   |      11 | 02:a3:57:c9:2a:93 | nic        |        3 | mac
 19 |      |            | resourcePool | 049424d4-2767-419f-8112-521e2076d2da |             | requested | 2015-08-14 19:09:17.071+00 |         |             | {}   | subnet    |       4 | 192.168.2.224     | ipAddress  |        8 | default
 20 |      |            | resourcePool | 45966250-4925-45be-9817-87926ed353fa |             | requested | 2015-08-14 19:09:17.085+00 |         |             | {}   | network   |      11 | 02:a3:57:10:6c:79 | nic        |        4 | mac
 21 |      |            | resourcePool | 6e4689e7-9bfb-4ddb-a314-ed935d99f434 |             | requested | 2015-08-14 19:09:17.595+00 |         |             | {}   | subnet    |       4 | 192.168.2.188     | ipAddress  |        9 | default
 22 |      |            | resourcePool | 769f5a68-4d78-4e32-ab48-bfb54d43279c |             | requested | 2015-08-14 19:09:17.605+00 |         |             | {}   | network   |      11 | 02:a3:57:f1:c8:da | nic        |        5 | mac
 23 |      |            | resourcePool | 2fc683a2-4237-4b53-83a3-621743ef6ac8 |             | requested | 2015-08-14 19:09:18.147+00 |         |             | {}   | subnet    |       4 | 192.168.2.89      | ipAddress  |       10 | default
 24 |      |            | resourcePool | aa778981-23a3-402b-8704-b01c97724018 |             | requested | 2015-08-14 19:09:18.158+00 |         |             | {}   | network   |      11 | 02:a3:57:30:fe:5a | nic        |        6 | mac
(23 rows)

You can see mysql has 26 rows and postgres only has 23. Pool 4 is missing 3 mac records. It happens sometimes. Mysql always has 26 rows, so I'm gussing it's purely related to postgres compatibility.

The results should be consistent right?

**Comment by dx9** [comment]
@ibuildthecloud I can't reproduce the situation I mentioned above anymore. Not sure how I got down that rabbit hole. 

The duplicate key errors appear to just be symptomatic of the query pattern. Upserts have landed in pg 9.5 and jOOQ is adding support for them so they'll disappear eventually. 

Fixed some tests that failed due to case sensitivity and order expectations.

Not sure if the full suite should run all the time. Seems like a drag to wait 40 mins for build results.

**Comment by rvion** [comment]
Is postgres support still on the roadmap ? :)

**Comment by ibuildthecloud** [comment]
@rvion The short answer is probably no.  I'd very much like to see Postgres work and be supported but from a practical such a thing is a low priority for me to tackle right now.  I'd love to see the community getting this working and we would accept the PR as long as it had CI integration so that we wouldn't break it in the future.

I think I dropped the ball on this PR because @dx9 got it working but I didn't merge.  Now this PR is out of date and needs to be updated.  Sorry for that.  If somebody can get it working again such that CI for postgres and MySQL upgrades are not broken by it, I would like to accept this PR.

**Comment by dx9** [comment]
cool, I'll take a look at updating it

**Comment by frekele** [comment]
+1

**Comment by frekele** [comment]
CATTLE_DB_CATTLE_POSTGRESQL_HOST: hostname or IP of PostgreSQL instance
CATTLE_DB_CATTLE_POSTGRESQL_PORT: 5432
CATTLE_DB_CATTLE_POSTGRESQL_NAME: Name of Database
CATTLE_DB_CATTLE_USERNAME: Username
CATTLE_DB_CATTLE_PASSWORD: Password

+1 \o/

**Comment by ibuildthecloud** [comment]
This PR is amazing.  @dx9 Any chance you can rebase?  We've updated the CI and moved to a new drone instance.  This drone supports matrix builds.  If you're still interested in working on this, I'd love to see postgres done as a matrix build.  If you can get the build green (or close), I will merge this.  We have plenty of people that would love to see Postgres and you've done such an incredible job getting this to work.  If we merge it then we won't keep breaking Postgres.

**Comment by ibuildthecloud** [comment]
@dx9 And I'm serious this time.  I'll really merge.  @deniseschannon will make sure I follow up :)

**Comment by dx9** [comment]
@ibuildthecloud Sure, will do. Soonish.

**Comment by ibuildthecloud** [comment]
@dx9 Thanks

**Comment by deniseschannon** [comment]
@dx9 Whenever you get a chance to rebase, please make sure to ping me and I'll bug @ibuildthecloud

**Comment by dx9** [comment]
@deniseschannon @ibuildthecloud Rebased. Thanks for looking at it.

**Comment by ibuildthecloud** [comment]
@dx9 This looks great.  I see you made a couple changes to some tests where we were mis-correctly relying on the DB order in the result.  Can you make the same changes to `tests/integration-v1/` so that the posgres v1 tests pass too?   There's one exception I'm seeing in the logs that is concerning
```java
2016-09-28 01:54:49,301 ERROR [:] [] [] [] [erviceReplay-18] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [externalevent.create:6300] on [3] org.jooq.exception.InvalidResultException: Cursor returned more than one result
	at org.jooq.impl.Utils.fetchOne(Utils.java:950) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:470) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2372) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.findOne(JooqObjectManager.java:346) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.findOne(JooqObjectManager.java:352) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.externalevent.ExternalEventPreCreate.handle(ExternalEventPreCreate.java:34) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:427) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:378) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:54) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:471) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:308) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:247) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
```

That bug might be tricky to track down.

**Comment by dx9** [comment]
@ibuildthecloud 

Yep, updated v1 tests.

Ya reproducing could be tough. I haven't seen that exception before and I've run this a lot. :) Hard to know if it is related to this change set.

**Comment by dx9** [comment]
@ibuildthecloud That error occurs on the mysql build. However it does not appear to cause any test failures.

**Comment by ibuildthecloud** [comment]
@dx9 I merged #2028 plus you're hitting a couple of issues that are already fixed on master.  Can you rebase?  There is one failing test right now that has me concerned, hopefully it will go away after a rebase.

**Comment by ibuildthecloud** [comment]
I've merged this even if it's not perfect (although I don't really see any fault with it).  I just don't want master to break postgres again (which I accidentally just did and then reverted).  Merging this will help us not break postgres again.

**Comment by dx9** [comment]
@ibuildthecloud Awesome! Love that you guys are open to it.

**Comment by frekele** [comment]
What is the procedure for using Rancher v1.2.0 with postgresql?

I have not found documentation for the correct usage, either a migration from mysql to postgresql.

Could inform me?

**Comment by mcanevet** [comment]
You should use `CATTLE_DB_CATTLE_DATABASE=postgres`, than you can set `CATTLE_DB_CATTLE_POSTGRES_HOST`, `CATTLE_DB_CATTLE_POSTGRES_PORT` and `CATTLE_DB_CATTLE_POSTGRES_NAME`

**Comment by frekele** [comment]
@mcanevet Thank you for your feedback.

I saw that the merge was made, but I did not see anything talking about its release.
Is it stable equal mysql for production use?

**Comment by longwuyuan** [comment]
@mcanevet @frekele , noobie non-developer here, going into production with Rancher+Kubernetes, all because of the blessed work from your teams. Gratitude. Intend to use Postgres externaldb with Rancher.

Can I actually use Kubernetes environment even though there is a "CATTLE" in all the CATTLE_DB_CATTLE.... variables. That "CATTLE" is just a variable_name is'nt it ?

**Comment by frekele** [comment]
@longwuyuan, with mysql you can use like this example with docker compose:
```
rancher-server:
  image: rancher/server:stable
  restart: always
  ports:
    - 8080:8080
  environment:
    - CATTLE_DB_CATTLE_MYSQL_HOST=myhost.example.com
    - CATTLE_DB_CATTLE_MYSQL_PORT=3306
    - CATTLE_DB_CATTLE_MYSQL_NAME=cattle
    - CATTLE_DB_CATTLE_USERNAME=cattle
    - CATTLE_DB_CATTLE_PASSWORD=password

nginx-rancher:
  image: my-nginx-proxy-rancher:stable
  restart: always
  ports:
    - 80:80
    - 443:443
  links:
    - rancher-server
```
Or direct with docker only:
```
sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server \
    --db-host myhost.example.com --db-port 3306 --db-user username \
    --db-pass password --db-name cattle
```

According with the documentation v1.0: 
https://docs.rancher.com/rancher/v1.0/en/installing-rancher/installing-server/#using-an-external-database

According with the documentation v.1.2: 
https://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/#launching-rancher-server---single-container---external-database

But postgresql I'm not sure. 😞

**Comment by vincent99** [comment]
@frekele the first "CATTLE_" is a prefix for all the environment variables and the second is the name we refer to the main database by.  So yes they are just names.  Kubernetes itself uses etcd as a database, and both kubernetes and etcd are started and managed by Cattle.

**Comment by frekele** [comment]
@vincent99 Thanks for your explanation.

Could you tell me if it is safe (reliable) to use Postgresql as a substitute for Mysql or should we wait for a future release?
I would love to change to postgresql, what would you recommend?

Thank you

**Comment by vincent99** [comment]
If you read above you'll see we merged this basically to get it in for integration with testing and to stop making the poor author rebase the PR at the time.  There are no docs and I don't think our QA even knows this exists, let alone tested it for 1.2.

So there is nothing wrong with running postgres as far as I know, but anyone running now is the guinea pig.  Needless to say if you're looking for stability, you should stick to MySQL.

**Pull request merged**
