### PR TITLE
Update to latest machine parameters [v0.4.1] + packet drivers

### PR DESCRIPTION
**Pull request by wlan0**
@cjellick @will-chan

### CODE REVIEW

**Comment by wlan0** [comment]
Unrelated test failure - test_link_remove_instance_restart

**Comment by cjellick** [comment]
lgtm

**Comment by cjellick** [comment]
actually, should we upgrade the machine version in this pr as well?
...and the gms version for that matter as well

**Comment by wlan0** [comment]
@cjellick yes, we should.

**Comment by will-chan** [comment]
LGTM

**Comment by cjellick** [comment]
reLGTM

**Pull request merged**
