### PR TITLE
Fuzzy search for LB hostname routing rules

### PR DESCRIPTION
**Pull request by alena1108**
Path and domain can be appended with condition. Condition format {condition}. Example:
 * example.com{end}/path{beg}=81

supported prefixes:

* beg (prefix match)
* dir (subdir match)
* dom (domain match)
* end (suffix match)
* reg (regex match)
* sub (substring match)

Description for all prefixes can be found here:

https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#7.3.6-req.hdr

Default value - exact match

### CODE REVIEW

**Comment by alena1108** [comment]
@vincent99 @ibuildthecloud ^^

**Comment by vincent99** [comment]
oy... This is definitely useful but I hate that the targets are crazy label strings already, and this is 2 more options for both the API and UI to parse and stringify in separate languages and attempt to explain to a human in docs.

Can we continue discussing/work on making this kind of thing first-class API and YAML fields?  e.g. https://github.com/rancher/rancher/issues/2590

**Comment by alena1108** [comment]
@vincent99 that would be the best, but I'm not sure when I can get to do that major LB refactoring. As fuzzy search is one of the most frequently requested features, so I've decided to give this PR a try.

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/cattle/pull/1104

**Pull request closed without merging**
