### PR TITLE
Change value datatype to varchar H2

### PR DESCRIPTION
**Pull request by mrajashree**
This PR changes datatype of `value` in table `setting` to `VARCHAR` for h2
Also changes datatypes of all H2 columns that are `CLOB` to `VARCHAR`

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Does the same work with just one changset element?

**Comment by prachidamle** [comment]
Do the other constraints stay intact on the columns after modifying datatype?

**Comment by mrajashree** [comment]
@ibuildthecloud with just one changeset as in all `modifyDataType` statements under one changeset? I haven't tried, should I?
@prachidamle yes the constraints stay intact

**Comment by cjellick** [comment]
@mrajashree yes, try it with one changeset element containing all the modifyDataType elements. Liquibase works in changeset chunks, computing whether or not a changeset has been ran based off of a combo of the id and author. I'm guessing @ibuildthecloud wants a single changeset element to cut down on the number of changes liquibase is computing and just because these make sense as a logical group.

Also, verified that you got them all:
```
$ mysqldump --no-data --compact -u cattle -p cattle > dump.sql
$ grep -i text dump.sql | wc -l
      87
```

**Comment by mrajashree** [comment]
@ibuildthecloud @cjellick tried it with one changeset element and it works

**Comment by cjellick** [comment]
Cool. We need to run this through drone before merging, but looks good otherwise. Want to remove the WIP from the title?

**Comment by mrajashree** [comment]
The TFs are `test_service_affinity_rules_w_policy`, `test_volume_remove_on_purge`, `test_edit_host_label`, `test_ip_pool_associate`, `test_remove_network_from_container`, `test_link_remove_restore`, `test_ipsec_nic_activate` and `test_docker_bind_address`. They all seem unrelated/known errors
@cjellick

**Comment by cjellick** [comment]
LGTM. test failures unrelated and i ran H2 locally and settings seem to be working correctly. thanks @mrajashree

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
