### PR TITLE
add drivername field to the storagepool resource in the db

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud @cjellick

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
rebase?  I just merged a DB change.

**Comment by wlan0** [comment]
rebased

**Comment by ibuildthecloud** [comment]
Tests are failing in an odd way.  I wonder if master is broken.

**Comment by ibuildthecloud** [comment]
Oh wait, no.  It's a legit failure.  You need to update auth.

**Comment by wlan0** [comment]
@ibuildthecloud I did not change the registry resource. The failure seems unrelated

**Comment by ibuildthecloud** [comment]
Hmm, but master isn't broken....

**Comment by ibuildthecloud** [comment]
@wlan0 a registry is a sub type of a storage pool

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
