### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by alena1108**
1) Corrected fix for scale import to rancher.yml

https://github.com/rancher/rancher/issues/1842

2) Fixed registering host for healtcheck:

https://github.com/rancher/rancher/issues/1917

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
can you rebase

**Comment by alena1108** [comment]
@ibuildthecloud rebased, but have to fix the newly added test

**Comment by ibuildthecloud** [comment]
@alena1108 Is this all good for merging?

**Comment by alena1108** [comment]
@ibuildthecloud yes

**Pull request merged**
