### PR TITLE
WIP remove scalepolicy from cattle

### PR DESCRIPTION
**Pull request by wlan0**
@alena1108

### CODE REVIEW

**Comment by wlan0** [comment]
addresses https://github.com/rancher/rancher/issues/6832

**Comment by alena1108** [comment]
@wlan0 could you also add the same logic - check scalePolicy field presence in addition to checking the desired scale - [here](https://github.com/rancher/cattle/blob/587e3b47a989f2f64da5fe669e5ddc36f565d082/code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java#L177)?

**Comment by wlan0** [comment]
two tests Failed, both are unrelated to this change - 

```
test_container_ha_remove
test_register_multiple_physical
```

**Comment by alena1108** [comment]
Closing this PR for now as scale policy will remain in cattle, it just has to be refactored

**Pull request closed without merging**
