### PR TITLE
Support proxy protocol

### PR DESCRIPTION
**Pull request by cjellick**

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Well thanks a whole new failure I've never seen.  Obviously unrelated??? Is websocket-proxy even used in the integration tests?

**Comment by cjellick** [comment]
@ibuildthecloud seems unrelated. Rebuilding to confirm. WSP is actually on in the cattle builds, but it is only working in its reverse proxy capacity.

**Comment by cjellick** [comment]
Got offline LGTM from @ibuildthecloud

**Comment by cjellick** [comment]
Addresses issue https://github.com/rancher/rancher/issues/1812

**Pull request merged**
