### PR TITLE
Generate uuid for the backend using domain/hostname

### PR DESCRIPTION
**Pull request by alena1108**
https://github.com/rancher/rancher/issues/1514

### CODE REVIEW

**Comment by alena1108** [comment]
@sonchang @ibuildthecloud

**Comment by sonchang** [comment]
LGTM.  Although, curious since I don't have much background.  Is it possible to have multiple LBs for different ports?

**Comment by alena1108** [comment]
I'm open for suggestions on better way to generate unique integer hash based on 2 strings. The replaced hashcode generated the same hashes for combinations like:

service2.html/www.abc2.com and service1.html/www.abc3.com generated the same hashcodes

**Comment by alena1108** [comment]
@sonchang here we generate the unique backend on the load balancer based on the hostName/path.

**Comment by sonchang** [comment]
Thx!  LGTM

**Pull request merged**
