### PR TITLE
add lastExitCode feature

### PR DESCRIPTION
**Pull request by StrongMonkey**
1. add lastExitcode for container api fields
2. auto-populate exitcode for containers if a stop or die event comes in

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/rancher/agent/pull/227

**Comment by StrongMonkey** [comment]
@cjellick add back-up logic in ping response also.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/5978

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/9209

**Comment by cjellick** [comment]
See my comments in your agent PR. Implementation needs to be changed to NOT be part of ping logic. Inspecting containers during ping is too expensive

**Comment by alena1108** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches. Closing as the corresponding issue is closed.

**Pull request closed without merging**
