### PR TITLE
SSL Termination bug fixes

### PR DESCRIPTION
**Pull request by alena1108**
1) Schedule LB update on cert.remove only when lb is active

https://github.com/rancher/rancher/issues/1897

2) Propagate error message thrown by certificate validation code to the API

https://github.com/rancher/rancher/issues/1900

3) Bug in update load balancer

https://github.com/rancher/rancher/issues/1899

4) Cleanup certificates dir before applying new certs

https://github.com/rancher/rancher/issues/1904

5) Disallow cert removal when assigned to the LB service

https://github.com/rancher/rancher/issues/1906

Also fixed some NPE noticed in ServiceMetadataInfoFactory.java

### CODE REVIEW

**Comment by cjellick** [comment]
flake8 fail

**Comment by alena1108** [comment]
@cjellick  fixed, thank you

**Comment by cjellick** [comment]
LGTM

**Comment by sonchang** [comment]
LGTM

**Pull request merged**
