### PR TITLE
Update build cattle

### PR DESCRIPTION
**Pull request by cloudnautique**

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
You get this error running bootstrap

`Running ./bootstrap ................tar (child): xz: Cannot exec: No such file or directory`

Odd thing is I don't know why that doesn't fail the build, but looks like we need xz-utils.

**Comment by ibuildthecloud** [comment]
Oh wait... it did fail the build.

**Comment by cloudnautique** [comment]
Yeah, its missing xz-utils.. building an update..

**Comment by cloudnautique** [comment]
Updating in another pr. Will skip this one.

**Pull request closed without merging**
