### PR TITLE
Retrive token that is the newest non expired token.

### PR DESCRIPTION
**Pull request by hibooboo2**

### CODE REVIEW

**Comment by sonchang** [comment]
LGTM.  Feel bad missing it the first time around

**Comment by cjellick** [comment]
This brings up the fact that we are definitely missing tests that exercise token expiration. I'm trying to think how we could test this.

**Comment by cjellick** [comment]
I will LGTM so as to unblock the release an this is obviously the right fix, but we should figure out how to explicitly test token expiration.

**Comment by hibooboo2** [comment]
Validation test. That changes the token expiry setting to something small with api. Then trys  to auth with expired token. I will right a validation test and submit a pr right now.

**Comment by hibooboo2** [comment]
Actually I will do it as an integration test and it can be tested when we implement localauth.

**Comment by cjellick** [comment]
That would immediately expire all tokens and if another token were used (if we run concurrently) those tests would fail, right?

**Pull request merged**
